### ISSUE TITLE
Issue on page /new_articles/Acontia_trabealis.html

### ISSUE THREAD

**Issue by vijaybarve** [wikiproject-biodiversity/wikiproject-biodiversity.github.io#4]
[Emmelia_trabealis](https://en.wikipedia.org/wiki/Emmelia_trabealis) is a synonym.

**Comment by andrawaag** [comment]
Created a taxon synonym statement: https://www.wikidata.org/wiki/Q22102741#P1420
Which should solve this issue. This species should no longer be listed in the jupyternotebook on missing Wikipedia articles
