### ISSUE TITLE
Issue on page /new_articles/Syricoris_lacunana.html

### ISSUE THREAD

**Issue by vijaybarve** [wikiproject-biodiversity/wikiproject-biodiversity.github.io#7]
[Syricoris lacunana](https://en.wikipedia.org/wiki/Syricoris_lacunana) article is present

**Comment by andrawaag** [comment]
There is a mismatch between the scientific label and the name used in both the header the sitelinks: https://www.wikidata.org/wiki/Q147963#P225

**Comment by andrawaag** [comment]
Created a new wikidata item for [Syricoris_lacunana](https://www.wikidata.org/wiki/Q115790206) and created a statement pointing to the taxon synonym. This should fix the issue and on the next build of the jupyterbook, this should not be listed
