### ISSUE TITLE
Issue on page /new_articles/Felis_catus.html

### ISSUE THREAD

**Issue by larsgw** [wikiproject-biodiversity/wikiproject-biodiversity.github.io#8]
I suppose https://www.wikidata.org/wiki/Q146 is modelled incorrectly? I'd expect items in the Q1-Q999 range to have been looked at thoroughly though.

**Comment by larsgw** [comment]
There's https://www.wikidata.org/wiki/Q20980826 for the taxon, which was split off as per https://www.wikidata.org/w/index.php?title=Wikidata_talk:WikiProject_Taxonomy/Archive/2017/03#Cats

**Comment by andrawaag** [comment]
Fixed by adding a new rule to the sparql query identifying links between taxa and their Wikipedia article in: https://github.com/wikiproject-biodiversity/wikiproject-biodiversity.github.io/blob/master/iNaturalistWikiprojectBiodivBook/list_missing_articles.ipynb
